name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.7"
          - "3.0"
          - "3.1"
        rails:
          - "5.2"
          - "6.0"
          - "6.1"
          - "7.0"
        exclude:
          - ruby: "2.5"
            rails: "7.0"
          - ruby: "2.5"
            rails: "6.1"
          - ruby: "2.5"
            rails: "6.0"
          - ruby: "2.7"
            rails: "5.2"
          - ruby: "3.0"
            rails: "5.2"
          - ruby: "3.1"
            rails: "5.2"

    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test
        run: bundle exec appraisal ${{ matrix.rails }} rspec
